{ pkgs, ... }:

{
  nixpkgs.hostPlatform = "aarch64-darwin";

  system.primaryUser = "benjamin";
  users.users.benjamin = {
    name = "benjamin";
    home = "/Users/benjamin";
  };

  nix = {
    package = pkgs.lix;
    settings.experimental-features = [
      "nix-command"
      "flakes"
    ];
  };

  programs.zsh.enable = true;

  fonts.packages = [ pkgs.jetbrains-mono ];

  homebrew = {
    enable = true;

    brews = [ "mas" ];

    casks = [
      "battle-net"
      "chatgpt"
      "codex"
      "discord"
      "figma"
      "google-chrome"
      "league-of-legends"
      "linearmouse"
      "minecraft"
      "nvidia-geforce-now"
      "rode-connect"
      "steam"
      "teamviewer"
      "telegram"
      "visual-studio-code"
    ];

    masApps = {
      Numbers = 361304891;
      WhatsApp = 310633997;
    };

    onActivation = {
      autoUpdate = false;
      cleanup = "none";
      upgrade = false;
    };
  };

  system.defaults = {
    dock = {
      autohide = true;
      show-recents = false;
      mru-spaces = false;
      minimize-to-application = true;
      tilesize = 32;
    };

    finder = {
      AppleShowAllExtensions = true;
      AppleShowAllFiles = true;
      ShowPathbar = true;
      ShowStatusBar = true;
      _FXShowPosixPathInTitle = true;
      CreateDesktop = false;
    };

    NSGlobalDomain = {
      AppleInterfaceStyle = "Dark";
      InitialKeyRepeat = 15;
      KeyRepeat = 2;
      NSAutomaticCapitalizationEnabled = false;
      NSAutomaticSpellingCorrectionEnabled = false;
    };

    screencapture = {
      location = "/Users/benjamin/Pictures/Screenshots";
      type = "png";
    };

    CustomUserPreferences = {
      "com.apple.dock"."size-immutable" = true;

      # TODO: Import assets/terminal/GitHub Dark.terminal before selecting this
      # custom profile in Terminal. The binary profile is intentionally not
      # generated by Nix.
      "com.apple.Terminal" = {
        "Default Window Settings" = "GitHub Dark";
        "Startup Window Settings" = "GitHub Dark";
      };
    };
  };

  system.stateVersion = 6;
}
